name: Selenium Tests

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8

      - name: Set up Chrome and Chromedriver
        run: |
          choco install googlechrome -y
          choco install chromedriver -y

      - name: Build and test
        run: mvn test
